### PR TITLE
Add an as.character method for crayon objects

### LINKED ISSUE #44: Ideas to make it easier to style text in conjunction with glue
Ideally it would be nice if something like the following syntax would work.

```r
library(crayon)
glue::glue("{blue}foo{red}bar{reset}baz")
```

I think it may be possible by defining a `as.character.crayon` method that just outputs the escapes for the crayon object (if any).

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #44

### CODE REVIEW

**Comment by jimhester** [comment]
This is a simple way to make crayon work better with glue today, maybe we can figure out a nicer syntax to handle the resetting in the future.

**Comment by gaborcsardi** [comment]
The reset is problematic, because it does not nest. It resets everything. So you cannot (say) set the color of a big block to grey at the beginning, and still keep the emphasised words scattered throughout the text. `crayon` can do this:

```r
cat(green(
  'I am a green line ' %+%
  blue$underline$bold('with a blue substring') %+%
  ' that becomes green again!\n'
))
```

It would be nice to have a syntax that nests. Usually templating engines have end tags, e.g. 
```
"{red}Warning:{endred} this is a warning message"
```

Or just 
```
"{red}Warning:{end} this is a warning message"
```
if the tags are properly nested.

How about we add an unary minus operator to crayon styles? Then you could write this:
```
glue("{red}Warning:{-red} this is a warning message")
```
because the `as.character(-red)` would just undo the color. You still cannot restore a different color, though.

**Comment by jimhester** [comment]
unary minus sounds good to me

**Comment by gaborcsardi** [comment]
Can you nest braces in `glue`? 
```
glue("{grey{a big of test with some {red}special{-red} words}")
```
I am kidding.... mostly.

**Comment by jimhester** [comment]
Not currently, we could change the parser to do this potentially, but it would complicate things quite a bit, it is also not clear to me how to do it, as `grey` could be a user defined function or `blue$underline$bold`.

**Comment by gaborcsardi** [comment]
How about just postprocessing the output of glue with sg, so that the nesting the be done properly? E.g. 
```
ansi(glue(...))
```

**Comment by jimhester** [comment]
I added unary minus, I think it is fairly nice...

**Comment by hadley** [comment]
I wonder if we could have a minor markdown variant for specifying colour? Markdown already handles italic and bold.

**Comment by gaborcsardi** [comment]
OK. Sorry, let me ponder this a bit. I would really prefer to same bg that nests properly, so that we can write: 
```
{bold}A title of a very important piece{-bold}

{grey}
Lorem ipsum dolor sit amet, consectetur {bold}adipisicing{-bold} elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat 
{bold}cupidatat{-bold} non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
{-grey}
```

We can introduce some custom ANSI sequence, but then we need to post-process the output.

**Comment by hadley** [comment]
If you like that style, why not just make it xml and then we don't need a custom parser?

```xml
<b>A title of a very important piece</b>

<grey>
Lorem ipsum dolor sit amet, consectetur <b>adipisicing</b> elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation 
ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat 
<b>cupidatat</b> non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</grey>
```

**Comment by jimhester** [comment]
The main problem with xml is people will think it is HTML and then want more features.

The current PR nests for non-like entities, so bold and colors nest fine, but colors just don't nest with each other. I think this is fine, it is the same way ANSI escapes work in bash prompts.

**Comment by gaborcsardi** [comment]
>  it is the same way ANSI escapes work in bash prompts.

That's true, but the point if `crayon` is that it provides an API that is  better than that.

**Comment by gaborcsardi** [comment]
How about we turn this around, and provide a function in `crayon`, called `ansiglue`, that does the post-processing, so we could do proper nesting?

**Comment by gaborcsardi** [comment]
So it would be the same syntax, with brackets, and everything from `glue` would work (we just call `glue::glue`), but then `crayon` post-processes the closing `-`  crayon tags, to make sure that we nest properly?

**Comment by gaborcsardi** [comment]
@jimhester so I suppose you are not crazy about `ansiglue`?

**Comment by jimhester** [comment]
I just don't think there is a great benefit to the added complexity, most of the time you are not doing nesting.

 I agree crayon's functional interface is nicer so I imagine people will just use that directly if they really need the nesting behavior.

**Comment by gaborcsardi** [comment]
OK. Let's see. We can always add it later.

**Pull request merged**
